### ISSUE TITLE
inline images don't respect font scaling

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-tagged-text#179]
`Text <wide>goes <panda /> here</wide>`

wide : { fontScaleWidth : 2 }

<img width="646" alt="Screen Shot 2021-11-08 at 2 26 29 PM" src="https://user-images.githubusercontent.com/170009/140812942-49153725-14c8-4406-b369-2bf4f70fe12d.png">

**Comment by mimshwright** [comment]
If we're talking about inline images, It makes sense that they wouldn't scale since that's what HTML does. But since we're calling these `icons` I think it makes sense to have them scale. Since it's kind of on the edge, I'd probably just add a flag to the options to be able to disable this. 

Ideally, I'd like to add the ability to set height and width of an image (#53)

**Comment by rizen** [comment]
Sorry, I forgot that there was the inline image mode as I don’t use that, so yes I mean icons. 

I also just noticed that my tags are hidden in the original post. 

Have no opinion on #53

**Comment by mimshwright** [comment]
I added this in version 2.4.0. I didn't publish yet to npm cuz I want to make  sure there are no unexpected issues. But the tests are passing so far!
