### ISSUE TITLE
undocumented features

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-tagged-text#193]
The following are not documented in the readme:

letterSpacing
lineSpacing

Mentioned, but not in the list of properties:

wordWrapWidth
fontSize

**Comment by mimshwright** [comment]
@rizen I didn't document all of these properties in the readme because they all exist in the original `PIXI.TextStyle` class. However, I'm going to add an additional line to clarify this.

<img width="916" alt="Screen Shot 2022-02-22 at 13 48 13" src="https://user-images.githubusercontent.com/141928/155225611-40ef1612-c068-4c3d-bc4d-a775b89559e1.png">
