### ISSUE TITLE
Texture memory leak

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-tagged-text#245]
There is a texture memory leak in TaggedText.  It's easy to prove using this incantation:

```console.log(Object.keys(PIXI.utils.TextureCache).length, PIXI.utils.TextureCache)```

This is my sample text: 

```<gold>test</gold>```

If you measure the number of textures using the above, then pass any old text into PIXI.Text and measure again, and then destroy() the object the first and last values match.

However, if you do the same with TaggedText it leaves behind a few textures.

Here's what I can prove:

- TaggedText is leaking textures as described above.
- This is happening during drawing, because if you if you turn on skipDraw and don't call draw() then you don't have the problem.
- drawWhitespace has some effect on this, because if you turn it off you get less losses.  
- This has nothing to do with imgMap because you get the same number of losses whether you pass in an imgMap or not.
- The styles config also has no impact, as you get the same number of losses whether you pass in {} or a full style config.
- It has something to do with word breaks, because if you use tags or two words like "test test" then you get losses, but if you use a single word like "test" then you get no losses.

**Comment by mimshwright** [comment]
Should be fixed now in v3.7.0

**Comment by mimshwright** [comment]
@rizen In case you're interested, the problem was that by default, `destroy()` wasn't destroying the child textures correctly unless you pass either `true` or `{children: true, texture: true}` as parameters. That's actually default behaviour for Pixi but in this case, it makes more sense to have it delete all its children too. Now it does (unless you explicitly tell it not to). 

However, I ran into an issue with the images / icons being deleted when I did this. To avoid loading these images each time you destroy a text field that uses them, I exempted them from being destroyed unless you explicitly call `destroyImgMap()`. 

There's a new section in README that essentially covers what this comment says. 

If you want to try testing this, you can get the source code, use `yarn demo` and navigate to `memory.html`. There are additional flags you can fiddle with in the html file to adjust how the tests are run.

**Comment by mimshwright** [comment]
Showing results of test:

![mem test](https://user-images.githubusercontent.com/141928/170602168-caf2c0f0-6b52-4378-833e-ace671d4768e.png)

```
...
Iterations: 4975
   Heap • size: 28MB • change: 4
   TextureCache • size: 38 • change: 0
   BaseTextureCache • size: 38 • change: 0
 
Iterations: 5000
   Heap • size: 24MB • change: -4
   TextureCache • size: 38 • change: 0
   BaseTextureCache • size: 38 • change: 0
 
FINISHED!
   Heap • Total gain: -8.91MB (-1.82KB/iteration)
   TextureCache • Total gain: 35 (0.01/iteration)
   BaseTextureCache • Total gain: 35 (0.01/iteration)
```

**Comment by rizen** [comment]
You are a beautiful man!

I'll try integrating this into Component.Studio tomorrow. Thank you so much for finding some time for this.

**Comment by mimshwright** [comment]
Your tip about the texture cache really helped me figure out where the issue was. Thanks!

**Comment by mimshwright** [comment]
For comparison, here's the results if you explicitly tell it NOT to destroy the cached text textures:
```
FINISHED!
   Heap • Total gain: 613.41MB (125.63KB/iteration)
   TextureCache • Total gain: 170001 (34.00/iteration)
   BaseTextureCache • Total gain: 170001 (34.00/iteration)
```

**Comment by rizen** [comment]
It totally worked! Nice job!
