### ISSUE TITLE
v2: Bulleted list

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-tagged-text#29]
I have a customer requesting bulleted lists. I have no idea how I would tackle this. Do you have an idea of what it would take to do this?  If it's not an ordeal, then I'll have you do it as part of v2.

**Comment by mimshwright** [comment]
The simplest way to do this now is just inserting a bullet character into the text like `"  • "` then your text. Beyond that quick solution, here are some ideas:

- pre-define a tag like `<li>` with `imgSrc: "bullet"`. I'm  pretty sure the text will flow to the right of the bullet. 
- Adding a real list tag with like ul / li would be kind of a pain since we don't have the concept of blocks nor do we have the concept of interrelated tags.
- Adding only <li> could work and I'd probably do it by adding a style property similar to the CSS rule `content` and the CSS selector `tag:before {}`. Something like `beforeContent` or `afterContent` that would let us inject content through the stylesheet.
- You could also write a function that transforms anything the user types into the text box and replace `<li>` with `"  • "`. That way they can't really tweak the structure of the bullet.

**Comment by mimshwright** [comment]
@rizen TL;DR, we probably don't have to change the component to make this work.
