### ISSUE TITLE
emoji support

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-tagged-text#71]
Mac OS has a feature where you can bring up an emoji keyboard with Control-Command-Space. I know Android and iOS also have this, and I'm sure windows does too. 

My users want to be able to use emoji's in their prototype games. The problem is that PTT seems to cut off the top of the emoji. Not sure why. Here's an example:

<img width="252" alt="Screen Shot 2021-05-27 at 9 57 36 AM" src="https://user-images.githubusercontent.com/170009/119849881-a2487800-bed2-11eb-92fa-48247560ba3f.png">

**Comment by mimshwright** [comment]
I'm not able to reproduce this issue. 

Here's my code and output...

<img width="680" alt="Screen Shot 2021-06-25 at 11 07 38" src="https://user-images.githubusercontent.com/141928/123467732-b05ae880-d5a5-11eb-9f6a-0e95a0e31ae9.png">
<img width="566" alt="Screen Shot 2021-06-25 at 11 07 48" src="https://user-images.githubusercontent.com/141928/123467739-b18c1580-d5a5-11eb-9469-247e2a313020.png">

@rizen Can you send me some sample code that is causing the issue or check to see if something else is clipping the text?

**Comment by mimshwright** [comment]
@rizen Are you still seeing this issue? If not, I'm ready to close it.

**Comment by mimshwright** [comment]
BTW, I'm pretty sure you can test this with windows using an onscreen keyboard (or by copy pasting emoji from another program)

**Comment by rizen** [comment]
I've figured out how to replicate it. The unfortunate bit is that I think this may be something broken at the browser level.

I've created a fiddle showing how it's broken: https://jsfiddle.net/plainblackguy/6r9hzgef/4/

It has to do with the base font that is loaded, in this case Bebas Neue from Google Fonts. However, I'm sure it will happen with some others too.

On Safari it looks like this:

<img width="559" alt="Screen Shot 2021-07-01 at 3 20 42 PM" src="https://user-images.githubusercontent.com/170009/124184955-e9043180-da7f-11eb-9a0c-088b33c1159a.png">

The top is cut off.

On Firefox it looks basically the same as Safari:

<img width="568" alt="Screen Shot 2021-07-01 at 3 23 07 PM" src="https://user-images.githubusercontent.com/170009/124185224-4d26f580-da80-11eb-9430-a99a9af525b1.png">



On Chrome it instead looks like:

<img width="570" alt="Screen Shot 2021-07-01 at 3 21 53 PM" src="https://user-images.githubusercontent.com/170009/124185074-1224c200-da80-11eb-9d2b-2d779bb242c1.png">

The top isn't cut off, but instead there's an extra gap between the first word and the emoji


Not sure why the browsers look different.

**Comment by mimshwright** [comment]
@rizen Well, this is not good. One of my concerns going into this was the need to generate print-ready bitmaps that  to match between the version the users create and the version you print. I (perhaps naïvely) hoped to avoid any cross browser issues and I had assumed that the best way to do this was to render the text into a canvas / pixi. But unfortunately, this proves that the way different browsers render into canvas, or at least how they render text and non-system fonts, is not 100% consistent. 

I expect ensuring the image matches what the client sees is critical for your app. To my knowledge and gut instinct,  this is not something we will be able to fix completely, but I can think of some ways it might be managed (more on that later). 

I created a detailed table of results on different browsers. 

https://airtable.com/shrvTQjAM5kx3Agkv

(most of them are using this slightly different fiddle as a starting point https://jsfiddle.net/sqa5uz3e/)

Notes:
- Windows, Mac, & Android (not in table) use different emojis
- Text all seems to work much better with system fonts (arial, segoe ui) than with custom font loaded at runtime
- I needed to reload JSFiddle each time to render the correct font since pixi's text was being created before the font loaded. In Chrome only I saw issues where the font loaded but had spacing issues until I loaded it again.
- This demo is running under Pixi 6.1
- I saved the images straight from the canvas in most cases but firefox and safari don't support this. I'll need to redo some of the firefox ones. The output from the canvas buffer seems to be slightly different from the screenshot version of the same browser.
- Some browsers render exactly the same (e.g. edge & chrome). Firefox appears to look almost exactly the same when i overlay a screen shot of firefox on a screenshot of edge. 
- Firefox looks blurry to me until I bump up the resolution to 2. 

Some more things to test to help get a better idea of what's going on:
- Test with a plain Text object (instead of PTT)
- Test with Pixi v5
- Test with other custom fonts
- Test with a delay to make sure custom font is loaded before creating the pixi app and rendering

Some ideas for possible fixes:
1. After doing a little research into which is the most stable / predictable browser, or which one is the most widely used by your users, require that they use, or at least proof the images pre-print on, a specific browser.
1. When your users save their files, generate a PNG from _their_ local version, save it and make that the canonical version. Likewise, you may want to record what version of browser they use to create their files and warn them if you detect that it has changed at any point. 
1. An extreme solution could be to render the image using an instance of a renderer running on the server and then serving that image to the user. Or I suppose you could generate them only before printing and show a proof (similar to number 1.)
1. We could search for emojis and automatically wrap them in special tags that would render them with a system font. 
1. You could search for emojis and automatically swap them out with png icon tags. 

Let me know what direction you think might be best for handling this one.

**Comment by mimshwright** [comment]
Update: 
Tested chrome with PIXI.Text instead of Pixi-Tagged-Text and it has the same issue with cutting off the top of emojis with Bebas Neue, looks good with Arial.

**Comment by rizen** [comment]
I would like to eliminate as much difference between browsers as possible, but ultimately I'm not terribly concerned about it. I knew going into this that using different browsers would likely produce slightly different results. So ultimately users will just have to stick with whatever browser they designed in first to continue doing renders. As long as it stays consistent for them, that's all that really matters. That said, if there's something we can do to mitigate some of the browser differences we should do that. 

Given that I'll answer your questions.

1. I think what I said above covers this.
2. This was always the plan. Their design view will generate an image and upload to the server which will then be processed into the printable PDFs.
3. Yeah, that's a no go. The whole point was go get away from server side rendering.
4. Ooh. That would be awesome if it's possible? If that's not possible, having a special tag that we could offer users to manually wrap them, or even if I just tell them to use Helvetica or whatever when wrapping emoji's would be fine. This is a good idea if that solves the problem.
5. I don't want to do that. They are forever coming out with new emoji's and that sounds like a maintenance nightmare.
6. Yeah, some fonts just have screwy parameters. I ran into this in my old version of CS too. Giving people tools to override problems when practical / possible was how I solved it. So it sounds like a reasonable way to go here too.

**Comment by mimshwright** [comment]
OK. So I'm hearing that we would do:
1. Not require / suggest a specific browser because...
2. For your app, the client will generate an image and that would be the one used for printing. 
3. No server side rendering. 
4. I'll try to wrap emojis in a tag making them a system font. 
5. If I were doing the swap with images route, I'd incorporate some well-upkept library like https://github.com/iamcal/js-emoji. But this is only a major need if you need cross-platform parity.
6. I'll create a new ticket for adding `fontProperties: { ascent: number, descent: number, fontSize: number }` to the stylesheet.

**Comment by mimshwright** [comment]
I've implemented the tag wrap thing in v2.2.4. Emojis are wrapped in a `<__EMOJI__>` tag and given a style `{fontFamily: "sans-serif"}`. However, it's not clear to me whether this actually fixes anything. The most notable thing it does is make the emojis move to the correct baseline while Bebas stays below it (on chrome / brave). https://jsfiddle.net/jr2mxvn8/

You can turn this feature on and off with `wrapEmoji: boolean` in the options object.

**Comment by mimshwright** [comment]
Just wanted to add that the JS Fiddle (or how it's loading the font and stuff) could be to blame for some of this?

Here's how Bebas Neue looks in JSFiddle in Brave on Mac. Notice the baseline position:
![image](https://user-images.githubusercontent.com/141928/125371076-d23dc480-e334-11eb-9441-7505cc789317.png)

This is the same font, same browser in my demo code. Looks fine: 
![image](https://user-images.githubusercontent.com/141928/125371028-b803e680-e334-11eb-97e3-ba6a55e05712.png)

**Comment by rizen** [comment]
I won't be able to look at this until Thursday. Just wanted to give you the heads up on the timeline.

**Comment by mimshwright** [comment]
Checking in on the status of this one. 
Main thing that concerns me is that the JSFiddle and the demo code I'm running locally look very different. https://github.com/mimshwright/pixi-tagged-text/issues/71#issuecomment-878681720

That could point to something to do with loading the fonts and creating the code for the PTT before the font is ready. Or possibly with how the code is all loaded through script tags or some other such thing.

**Comment by rizen** [comment]
Works perfectly in 2.2.7!
