### ISSUE TITLE
Feature: valign on individual pieces of text / images (currently only works on entire lines of text)

### ISSUE THREAD

**Issue by rizen** [mimshwright/pixi-tagged-text#9]
I know I said we didn't need valign on images in phase 1. But now that we're on to phase 2, let's get it done!

Get valignImg working for top, middle, baseline, and bottom.

**Comment by rizen** [comment]
If valign on images is working, then I can’t tell, because “bottom” doesn’t look like it goes down to a descender, I don’t know what middle is doing. Top does seem to work. Maybe I just don’t understand how they are supposed to work, and maybe there needs to be an extra option. 

<img width="195" alt="Screen Shot 2021-03-25 at 6 11 32 PM" src="https://user-images.githubusercontent.com/170009/112555410-23ca3f80-8d96-11eb-91ed-46891043d646.png">

Here's what I'm expecting, maybe my expectations are just wrong.

**baseline** - This seems to work as I'd expect. What I'm expecting is that the bottom of the icon is aligned with the baseline of the font.

**middle** - The icon should center itself between he ascender and decender of the font.

**bottom** - The icon's bottom should align at the bottom of the font descender. 

**top** - The icon's top should align at the top of the font ascender. 

If my expectations are wrong, then what I'd like is to have extra options added that will meet my expectations.

**Comment by mimshwright** [comment]
Current status

Icon images:
![image](https://user-images.githubusercontent.com/141928/112740507-907a4100-8f32-11eb-840e-ba5701c71b42.png)
![image](https://user-images.githubusercontent.com/141928/112740518-a982f200-8f32-11eb-93ca-af0c20c1ed74.png)


Inline images:
![image](https://user-images.githubusercontent.com/141928/112740467-22357e80-8f32-11eb-8e58-ae631552abae.png)
![image](https://user-images.githubusercontent.com/141928/112740523-b869a480-8f32-11eb-80f3-5f96c90fd911.png)

**Comment by mimshwright** [comment]
Looks like this is working but highlights an issue with vertical alignment where bottom valigned text without any descender or top valigned text with a lot of headspace in the font metrics looks kind of wack. But I don't know that it's worth the trouble to try to fix that, or even whether it's a real bug.

**Comment by mimshwright** [comment]
Please close if you're satisfied with how it's working.

**Comment by rizen** [comment]
Updated to the latest and still not getting the valign to work right.

<img width="203" alt="Screen Shot 2021-03-27 at 10 29 02 PM" src="https://user-images.githubusercontent.com/170009/112741481-e0193680-8f4b-11eb-8a31-011c8215613a.png">


Here's my text:

```
let text = `baseline <baseline imgSrc="thinking"></baseline>
top <top imgSrc="thinking"></top>
bottom <bottom imgSrc="thinking"></bottom>
middle <middle imgSrc="thinking"></middle>
`;
```

Here's my style:

```
const style = {
  default: {
    fontFamily: "Arial",
    fontSize: "24px",
    fill: "#000000",
    imgDisplay : 'icon',
  },
  top: { valign: "top" },
  middle: { valign: "middle" },
  bottom: { valign: "bottom" },
  baseline: { valign: "baseline" },          
}
```

What am I doing wrong?

**Comment by mimshwright** [comment]
I think what's going on is something to do with the tags being on only one word (or image in this case), rather than the entire line of text. I bet it's got some issue where it's not checking the whole line for the valign stuff. I'll try to set up a test for this. 

here's my example code for reference:
// Vertical Alignment
const valignStyle = {
  default: {
    fontFamily: "Arial",
    fontSize: "24px",
    fill: "#cccccc",
    align: "left",
    valign: "baseline",
  },
  code: {
    fontFamily: "Courier",
    fontSize: "36px",
    fill: "#ff8888",
  },
  small: { fontSize: "14px" },
  top: { valign: "top" },
  middle: { valign: "middle" },
  bottom: { valign: "bottom" },
  baseline: { valign: "baseline" },
  img: { imgSrc: "valignImg", imgDisplay: "inline" },
};
const valignImg = PIXI.Sprite.from("./icon.png");
let valign = new RichText(`<top><code>Top</code> <small>Vertical</small> <img/> Alignment.</top>

<middle><code>Middle</code> <small>Vertical</small> <img/> Alignment.</middle>

<bottom><code>Bottom</code> <small>Vertical</small> <img/> Alignment.</bottom>

<baseline><code>Baseline</code> <small>Vertical</small> <img/> Alignment.</baseline>`,
  valignStyle,
  { imgMap: { valignImg }, debug: true }
);
```

**Comment by rizen** [comment]
I've updated my text to this, and yes it works now. So your assessment is correct.

```
<baseline>baseline <thinking></thinking></baseline>
<top>top <thinking></thinking></top>
<bottom>bottom <thinking></thinking></bottom>
<middle>middle <thinking></thinking></middle>
```

**Comment by mimshwright** [comment]
@rizen Your example wasn't wrong though. I think that's still a bug.

**Comment by rizen** [comment]
I agree. Just confirming your thoughts.

**Comment by mimshwright** [comment]
This appears to be fixed since the last time we reviewed it. Probably part of #7 

<img width="1066" alt="Screen Shot 2021-06-25 at 11 41 36" src="https://user-images.githubusercontent.com/141928/123471227-53156600-d5aa-11eb-8077-9965c6fad9d9.png">
<img width="523" alt="Screen Shot 2021-06-25 at 11 41 07" src="https://user-images.githubusercontent.com/141928/123471231-5577c000-d5aa-11eb-95af-8b48eff2942e.png">

**Comment by mimshwright** [comment]
I wanted to double check this by setting the default text size to 12px (from 36) and also looks ok.

<img width="500" alt="Screen Shot 2021-06-25 at 11 45 40" src="https://user-images.githubusercontent.com/141928/123471615-e6e73200-d5aa-11eb-84c1-298d29e1698f.png">

**Comment by mimshwright** [comment]
@rizen Closing this for now. Please let me know if you're still seeing issues.
